# Generated by Django 5.2 on 2025-04-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodios',
            new_name='Episodio',
        ),
    ]
